EventosCatolicos/Controllers/ProfesionesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EventosCatolicos.Models;

namespace EventosCatolicos.Controllers
{
    public class ProfesionesController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Profesiones
        [Authorize(Roles = "Ver Profesiones,IT")]
        public ActionResult Index()
        {
            return View(_db.Profesiones.ToList());
        }

        // GET: Profesiones/Details/5
        [Authorize(Roles = "Ver Profesiones,IT")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesion profesion = _db.Profesiones.Find(id);
            if (profesion == null)
            {
                return HttpNotFound();
            }
            return View(profesion);
        }

        // GET: Profesiones/Create
        [Authorize(Roles = "Administrar Profesiones,IT")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profesiones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Profesiones,IT")]
        public ActionResult Create([Bind(Include = "Id,Nombre")] Profesion profesion)
        {
            if (ModelState.IsValid)
            {
                _db.Profesiones.Add(profesion);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(profesion);
        }

        // GET: Profesiones/Edit/5
        [Authorize(Roles = "Administrar Profesiones,IT")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesion profesion = _db.Profesiones.Find(id);
            if (profesion == null)
            {
                return HttpNotFound();
            }
            return View(profesion);
        }

        // POST: Profesiones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Profesiones,IT")]
        public ActionResult Edit([Bind(Include = "Id,Nombre")] Profesion profesion)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(profesion).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profesion);
        }

        // GET: Profesiones/Delete/5
        [Authorize(Roles = "Eliminar Profesiones,IT")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profesion profesion = _db.Profesiones.Find(id);
            if (profesion == null)
            {
                return HttpNotFound();
            }
            return View(profesion);
        }

        // POST: Profesiones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Eliminar Profesiones,IT")]
        public ActionResult DeleteConfirmed(int id)
        {
            Profesion profesion = _db.Profesiones.Find(id);
            _db.Profesiones.Remove(profesion);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventosCatolicos/Views/Profesiones/Create.cshtml
@using EventosCatolicos.Servicios
@model EventosCatolicos.Models.Profesion

@{
    ViewBag.Title = "Profesión";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Profesión</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelForRequired(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="clearfix"></div>
        <div class="form-group">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Profesiones", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Profesiones/Delete.cshtml
@model EventosCatolicos.Models.Profesion

@{
    ViewBag.Title = "Profesión";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Profesión</h2>

    <h3>@EventosCatolicos.Servicios.clsOpciones.SMensajeEliminar la profesion?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Profesiones", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default color-rojo @EventosCatolicos.Servicios.clsOpciones.SIconoEliminar" data-toggle="tooltip" title="Eliminar "></button>
            </div>
        }
    </div>
@section Scripts {
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}

EventosCatolicos/Views/Profesiones/Details.cshtml
@model EventosCatolicos.Models.Profesion

@{
    ViewBag.Title = "Profesión";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Profesión</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

        </dl>
    </div>
    <p>
        <div class="btn-group" role="group" aria-label="...">
            @Html.ActionLink(" ", "Index", "Profesiones", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
            @Html.ActionLink(" ", "Edit", "Profesiones", new { id = Model.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn btn-default " + @EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
        </div>
    </p>
    @section Scripts {
        </div>
        <script>
            $(document).ready(function() {
                $('[data-toggle="tooltip" ]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Profesiones/Edit.cshtml
@model EventosCatolicos.Models.Profesion

@{
    ViewBag.Title = "Profesión";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Profesión</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Id)

        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new {@class = "control-label"})
            @Html.EditorFor(model => model.Nombre, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Nombre, "", new {@class = "text-danger"})
        </div>

        <div class="form-group col-md-10">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Profesiones", null, new {data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon  glyphicon glyphicon-arrow-left color-verde"})
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }

    @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
</div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Profesiones/Index.cshtml
@model IEnumerable<EventosCatolicos.Models.Profesion>
@using GridMvc.Html
@{
    ViewBag.Title = "Profesión";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Profesión</h2>
    @if (User.IsInRole("Administrar Profesiones") || User.IsInRole("IT"))
    {
        <p>
            <a class="btn btn-default1" data-toggle="tooltip" title="Crear"
                href="@Url.Action("Create", new {controller = "Profesiones"})">
                <span class=" glyphicon glyphicon-plus color-verde" aria-hidden="true"></span>
                Crear
            </a>
        </p>
    }
    @Html.Grid(Model).Named("Profesiones").EmptyText("No hay elementos para mostrar").Columns(columns =>
    {
        columns.Add().Titled("Opciones").Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(e =>
            @<span>
                @if (User.IsInRole("Administrar Profesiones") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Edit", new { id = e.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn1 btn-default1 " + EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
                }
                @if (User.IsInRole("Ver Profesiones") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Details", new { id = e.Id }, new { data_toggle = "tooltip", title = "Detalles", @class = "btn1 btn-default1 color-azul" + EventosCatolicos.Servicios.clsOpciones.SIconoDetalles })
                }
                @if (User.IsInRole("Eliminar Profesiones") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Delete", new { id = e.Id }, new { data_toggle = "tooltip", title = "Eliminar", @class = "btn1 btn-default1 color-rojo " + EventosCatolicos.Servicios.clsOpciones.SIconoEliminar })
                }

            </span>).SetWidth(200);
        columns.Add(model => model.Id).Titled("Código").SetWidth(110);
        columns.Add(model => model.Nombre).Titled("Nombre").SetWidth(110);

    }).Filterable(true).WithMultipleFilters().Sortable(true).SetLanguage("es").Selectable(true).WithPaging(10);

    @section scripts
    {
    @Scripts.Render("~/bundles/gridmvc")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                pageGrids.Profesiones.lang = gridmvc.lang.es;
            });
        </script>
    }