EventosCatolicos/Controllers/ArchivosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EventosCatolicos.Models;

namespace EventosCatolicos.Controllers
{
    public class ArchivosController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Archivos
         [Authorize(Roles = "Ver Archivo,IT")]
        public ActionResult Index()
        {
            return View(_db.Archivos.ToList());
        }

        // GET: Archivos/Details/5
        [Authorize(Roles = "Ver Archivo,IT")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Archivo archivo = _db.Archivos.Find(id);
            if (archivo == null)
            {
                return HttpNotFound();
            }
            return View(archivo);
        }

        // GET: Archivos/Create
         [Authorize(Roles = "Adminsitrar Archivo,IT")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Archivos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Archivo,IT")]
        public ActionResult Create([Bind(Include = "Id,Nombre,Localizacion")] Archivo archivo)
        {
            if (ModelState.IsValid)
            {
                _db.Archivos.Add(archivo);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(archivo);
        }

        // GET: Archivos/Edit/5
        [Authorize(Roles = "Administrar Archivo,IT")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Archivo archivo = _db.Archivos.Find(id);
            if (archivo == null)
            {
                return HttpNotFound();
            }
            return View(archivo);
        }

        // POST: Archivos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Archivo,IT")]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Localizacion")] Archivo archivo)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(archivo).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(archivo);
        }

        // GET: Archivos/Delete/5
        [Authorize(Roles = "Eliminar Archivo,IT")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Archivo archivo = _db.Archivos.Find(id);
            if (archivo == null)
            {
                return HttpNotFound();
            }
            return View(archivo);
        }

        // POST: Archivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Eliminar Archivo,IT")]
        public ActionResult DeleteConfirmed(int id)
        {
            Archivo archivo = _db.Archivos.Find(id);
            _db.Archivos.Remove(archivo);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventosCatolicos/Views/Archivos/Create.cshtml
@using EventosCatolicos.Servicios
@model EventosCatolicos.Models.Archivo

@{
    ViewBag.Title = "Crear";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Crear</h2>


    @using (Html.BeginForm("Create", "Archivos", FormMethod.Post, new { @role = "form" }))
    {
        @Html.AntiForgeryToken()

        <h4>Crear un nuevo archivo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group col-sm-6 col-md-4">

            @Html.LabelForRequired(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelForRequired(model => model.Localizacion)
            @Html.EditorFor(model => model.Localizacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Localizacion, "", new { @class = "text-danger" })
        </div>
        <div class="clearfix"></div>
        <div class="form-group">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Archivos", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Archivos/Delete.cshtml
@model EventosCatolicos.Models.Archivo

@{
    ViewBag.Title = "Eliminar";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Eliminar</h2>

    <h3>Esta seguro que desea eliminar este archivo?</h3>
    <div>
        <h4>Archivo</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Localizacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Localizacion)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Archivos", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default color-rojo @EventosCatolicos.Servicios.clsOpciones.SIconoEliminar" data-toggle="tooltip" title="Eliminar "></button>
            </div>
        }
    </div>
    @section scripts
{
        

    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip" ]').tooltip();
        });
    </script>
}

EventosCatolicos/Views/Archivos/Details.cshtml
@model EventosCatolicos.Models.Archivo

@{
    ViewBag.Title = "Detalles";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Detalles</h2>

    <div>
        <h4>Archivo</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Localizacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Localizacion)
            </dd>

        </dl>
    </div>
    <p>
        <div class="btn-group" role="group" aria-label="...">
            @Html.ActionLink(" ", "Index", "Archivos", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
            @Html.ActionLink(" ", "Edit", "Archivos", new { id = Model.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn btn-default " + @EventosCatolicos.Servicios.clsOpciones.SIconoEditar  })
        </div>
    </p>
    @section scripts
{
      </div>
          <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip" ]').tooltip();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                pageGrids.Antecedentes.lang = gridmvc.lang.es;
            });
        </script>
    }

EventosCatolicos/Views/Archivos/Edit.cshtml
@model EventosCatolicos.Models.Archivo

@{
    ViewBag.Title = "Editar";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Archivos</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group col-sm-6 col-md-4">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-sm-6 col-md-4">
                @Html.LabelFor(model => model.Localizacion, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Localizacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localizacion, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-10">
                <div class="btn-group" role="group" aria-label="...">
                    @Html.ActionLink(" ", "Index", "Archivos", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon  glyphicon glyphicon-arrow-left color-verde" })
                    <button type="submit" class="btn btn-default imagenGuardar" data-toggle="tooltip" title="Guardar">
                        
                    </button>
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Archivos/Index.cshtml
@model IEnumerable<EventosCatolicos.Models.Archivo>
@using GridMvc.Html
@{
    ViewBag.Title = "Archivos";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Archivos</h2>
        @if (User.IsInRole("Administrar Archivos") || User.IsInRole("IT"))
        {
    <p>
        <a class="btn btn-default1" data-toggle="tooltip" title="Crear"
           href="@Url.Action("Create", new { controller = "Archivos" })">
            <span class="glyphicon glyphicon-plus color-verde" aria-hidden="true"></span>
            Crear
        </a>
        <a class="btn btn-default1" data-toggle="tooltip" title="Ver pantalla"
           href="@Url.Action("PantallaArchivo", new { controller = "Pacientes" })">
            <span class="glyphicon glyphicon-modal-window color-azul" aria-hidden="true"></span>
            Pantalla Archivo
        </a>
    </p>
        }
    @Html.Grid(Model).Named("Archivos").EmptyText("No hay elementos para mostrar").Columns(columns =>
    {
        columns.Add().Titled("Opciones").Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(e =>
            @<span>
                @if (User.IsInRole("Administrar Archivos") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Edit", new { id = e.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn1 btn-default1 " + EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
                }
                @if (User.IsInRole("Ver Archivos") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Details", new { id = e.Id }, new { data_toggle = "tooltip", title = "Detalles", @class = "btn1 btn-default1 color-azul" + EventosCatolicos.Servicios.clsOpciones.SIconoDetalles })
                }
                @if (User.IsInRole("Eliminar Archivos") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Delete", new { id = e.Id }, new { data_toggle = "tooltip", title = "Eliminar", @class = "btn1 btn-default1 color-rojo " + EventosCatolicos.Servicios.clsOpciones.SIconoEliminar })
                }
            </span>).SetWidth(200);
        columns.Add(model => model.Id).Titled("Código").SetWidth(110);
        columns.Add(model => model.Nombre).Titled("Nombre").SetWidth(110);
        columns.Add(model => model.Localizacion).Titled("Localización").SetWidth(110);

    }).Filterable(true).WithMultipleFilters().Sortable(true).SetLanguage("es").Selectable(true).WithPaging(10)

    @section scripts
{
        @Scripts.Render("~/bundles/gridmvc")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip" ]').tooltip();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                pageGrids.Archivos.lang = gridmvc.lang.es;
            });
        </script>
    }