EventosCatolicos/ViewModels/MunicipiosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventosCatolicos.ViewModels
{
    public class MunicipioViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(256)]
        public string Nombre { get; set; }

    }

    public class MunicipioInfoViewModel : MunicipioViewModel
    {
        [Required]
        public string Departamento { get; set; }
    }

    public class MunicipioModifyViewModel : MunicipioViewModel
    {
        public int DepartamentoId { get; set; }
    }
}

EventosCatolicos/Controllers/MunicipiosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EventosCatolicos.Models;
using EventosCatolicos.ViewModels;
using System.Threading.Tasks;


namespace EventosCatolicos.Controllers
{
    public class MunicipiosController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Municipios
        [Authorize(Roles = "Ver Municipios,IT")]
        public ActionResult Index()
        {
            var municipiosViewModel = _db.Municipios.Select(
                @municipio => new MunicipioInfoViewModel
                {
                    Id = @municipio.Id,
                    Nombre = @municipio.Nombre,
                    Departamento = _db.Departamentos.FirstOrDefault(d => d.Id == @municipio.DepartamentoId).Nombre
                }).ToList();
            return View(municipiosViewModel);
        }

        // GET: Municipios/Details/5
        [Authorize(Roles = "Ver Municipios,IT")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Municipio municipio = _db.Municipios.Find(id);
            if (municipio == null)
            {
                return HttpNotFound();
            }
            var municipioViewModel = new MunicipioInfoViewModel 
            {
                Id = municipio.Id,
                Nombre = municipio.Nombre,
                Departamento = _db.Departamentos.First(d => d.Id == municipio.DepartamentoId).Nombre
            };
            return View(municipioViewModel);
        }

        // GET: Municipios/Create
        [Authorize(Roles = "Administrar Municipios,IT")]
        public ActionResult Create()
        {
            ViewBag.DepartamentoId = new SelectList(_db.Departamentos, "Id", "Nombre", 1);
            return View();
        }

        // POST: Municipios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Municipios,IT")]
        public ActionResult Create([Bind(Include = "Id,Nombre,DepartamentoId")] MunicipioModifyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var municipio = new Municipio 
                {
                    Id = model.Id,
                    Nombre = model.Nombre,
                    DepartamentoId = model.DepartamentoId
                };
                
                _db.Municipios.Add(municipio);
                _db.SaveChanges();
                
                return RedirectToAction("Index");
            }

            ViewBag.DepartamentoId = new SelectList(_db.Departamentos, "Id", "Nombre", model.DepartamentoId);
            return View(model);
        }

        // GET: Municipios/Edit/5
        [Authorize(Roles = "Administrar Municipios,IT")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Municipio municipio = _db.Municipios.Find(id);
            if (municipio == null)
            {
                return HttpNotFound();
            }
            var municipioViewModel = new MunicipioModifyViewModel
            {
                Id = municipio.Id,
                Nombre = municipio.Nombre,
            };
            ViewBag.DepartamentoId = new SelectList(_db.Departamentos, "Id", "Nombre", 1);
            return View(municipioViewModel);
        }

        // POST: Municipios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrar Municipios,IT")]
        public ActionResult Edit([Bind(Include = "Id,Nombre,DepartamentoId")] MunicipioModifyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var municipio = new Municipio
                {
                    Id = model.Id,
                    Nombre = model.Nombre,
                    DepartamentoId = model.DepartamentoId
                };
                _db.Municipios.Add(municipio);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartamentoId = new SelectList(_db.Departamentos, "Id", "Nombre", model.DepartamentoId);
            return View(model);
        }

        // GET: Municipios/Delete/5
        [Authorize(Roles = "Eliminar Municipios,IT")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Municipio municipio = _db.Municipios.Find(id);
            if (municipio == null)
            {
                return HttpNotFound();
            }
            return View(municipio);
        }

        // POST: Municipios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Eliminar Municipios,IT")]
        public ActionResult DeleteConfirmed(int id)
        {
            Municipio municipio = _db.Municipios.Find(id);
            _db.Municipios.Remove(municipio);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventosCatolicos/Views/Municipios/Create.cshtml
@using EventosCatolicos.Servicios
@model EventosCatolicos.ViewModels.MunicipioModifyViewModel

@{
    ViewBag.Title = "Municipio";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Municipio</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelForRequired(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelForRequired(model => model.DepartamentoId,"Departamento")
            @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
        </div>

        <div class="clearfix"></div>
        <div class="form-group">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Municipios", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Municipios/Delete.cshtml
@model EventosCatolicos.Models.Municipio

@{
    ViewBag.Title = "Municipio";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Municipio</h2>

    <h3>@EventosCatolicos.Servicios.clsOpciones.SMensajeEliminar el municipio?</h3>
<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="btn-group" role="group" aria-label="...">
            @Html.ActionLink(" ", "Index", "Municipios", null, new {data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde"})
            <button type="submit" class="btn btn-default color-rojo @EventosCatolicos.Servicios.clsOpciones.SIconoEliminar" data-toggle="tooltip" title="Eliminar "></button>
        </div>
    }
</div>
@section Scripts {
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

    }
    

EventosCatolicos/Views/Municipios/Details.cshtml
@model EventosCatolicos.ViewModels.MunicipioInfoViewModel

@{
    ViewBag.Title = EventosCatolicos.Servicios.clsOpciones.SDetalle;
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Municipio</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Departamento)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Departamento)
            </dd>

        </dl>
    </div>
<p>
    <div class="btn-group" role="group" aria-label="...">
        @Html.ActionLink(" ", "Index", "Municipios", null, new {data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde"})
        @Html.ActionLink(" ", "Edit", "Municipios", new {id = Model.Id}, new {data_toggle = "tooltip", title = "Editar", @class = "btn btn-default " + @EventosCatolicos.Servicios.clsOpciones.SIconoEditar})
    </div>
</p>
@section Scripts{
    </div>
        <script>
            $(document).ready(function() {
                $('[data-toggle="tooltip" ]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Municipios/Edit.cshtml
@model EventosCatolicos.ViewModels.MunicipioModifyViewModel

@{
    ViewBag.Title = "Municipio";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Municipio</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(model => model.DepartamentoId, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("DepartamentoId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartamentoId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-10">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "Municipios", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon  glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }


@section Scripts {
    </div>
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/Municipios/Index.cshtml
@model IEnumerable<EventosCatolicos.ViewModels.MunicipioInfoViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Municipio";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Municipio</h2>
    @if (User.IsInRole("Administrar Municipios") || User.IsInRole("IT"))
    {
        <p>
            <a class="btn btn-default1" data-toggle="tooltip" title="Crear"
               href="@Url.Action("Create", new {controller = "Municipios"})">
                <span class=" glyphicon glyphicon-plus color-verde" aria-hidden="true"></span>
                Crear
            </a>
        </p>
    }
        @Html.Grid(Model).Named("Municipios").EmptyText("No hay elementos para mostrar").Columns(columns =>
    {
        columns.Add().Titled("Opciones").Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(e =>
            @<span>
                @if (User.IsInRole("Administrar Municipios") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Edit", new { id = e.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn1 btn-default1 " + EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
                }
                @if (User.IsInRole("Ver Municipios") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Details", new { id = e.Id }, new { data_toggle = "tooltip", title = "Detalles", @class = "btn1 btn-default1 color-azul" + EventosCatolicos.Servicios.clsOpciones.SIconoDetalles })
                }
                @if (User.IsInRole("Eliminar Municipios") || User.IsInRole("IT"))
                {
                    @Html.ActionLink(" ", "Delete", new { id = e.Id }, new { data_toggle = "tooltip", title = "Eliminar", @class = "btn1 btn-default1 color-rojo " + EventosCatolicos.Servicios.clsOpciones.SIconoEliminar })
                }
            </span>).SetWidth(200);
        columns.Add(model => model.Id).Titled("Código").SetWidth(110);
        columns.Add(model => model.Nombre).Titled("Nombre").SetWidth(110);
        columns.Add(model => model.Departamento).Titled("Departamento").SetWidth(110);

    }).Filterable(true).WithMultipleFilters().Sortable(true).SetLanguage("es").Selectable(true).WithPaging(10)
    @section scripts
{
        @Scripts.Render("~/bundles/gridmvc")
    </div>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                pageGrids.Municipios.lang = gridmvc.lang.es;
            });
        </script>
    }