EventosCatolicos/Controllers/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EventosCatolicos.Models;
using EventosCatolicos.Servicios;
using EventosCatolicos.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace EventosCatolicos.Controllers
{
    [Authorize(Roles = "IT,Admin")]
    public class UsersAdminController : Controller
    {

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // Add the Group Manager (NOTE: only access through the public
        // Property, not by the instance variable!)
        private ApplicationGroupManager _groupManager;
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationGroupManager>();
            }
            private set
            {
                _groupManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public ActionResult Index()
        {
            var usersList = UserManager.Users.Select(
                @user => new ApplicationUserViewModel
                {
                    Id = @user.Id,
                    PrimerNombre = @user.PrimerNombre,
                    SegundoNombre = @user.SegundoNombre,
                    PrimerApellido = @user.PrimerApellido,
                    SegundoApellido = @user.SegundoApellido,
                    UserName = @user.UserName,
                    Email = @user.Email
                });
            return View(usersList);

        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound("No se encontró el usuario");
            }
            var createdBy = await UserManager.FindByIdAsync(user.CreatedBy);
            var modifiedBy = await UserManager.FindByIdAsync(user.ModifiedBy);
            if (createdBy == null || modifiedBy == null)
            {
                user.CreatedBy = "";
                user.ModifiedBy = "";
            }
            else
            {
                user.CreatedBy = createdBy.UserName;
                user.ModifiedBy = modifiedBy.UserName;
            }
            

            var userViewModel = new DetailsApplicationUserViewModel
            {
                Id = id,
                PrimerNombre = user.PrimerNombre,
                SegundoNombre = user.SegundoNombre,
                PrimerApellido = user.PrimerApellido,
                SegundoApellido = user.SegundoApellido,
                UserName = user.UserName,
                Email = user.Email,
                CreatedBy = user.CreatedBy,
                CreatedAt = user.CreatedAt,
                CreatedFrom = user.CreatedFrom,
                ModifiedBy = user.ModifiedBy,
                ModifiedAt = user.ModifiedAt,
                ModifiedFrom = user.ModifiedFrom,
                GroupsList = await GroupManager.GetUserGroupsAsync(id)
            };
            userViewModel.GroupsCount = userViewModel.GroupsList.Count();
            return View(userViewModel);
        }


        // Create user
        public async Task<ActionResult> Create()
        {
            ViewBag.GroupsList = new SelectList(await GroupManager.Groups.ToListAsync(), "Id", "Name");
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(ApplicationUserViewModel model, params string[] selectedGroups)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    PrimerNombre = model.PrimerNombre,
                    SegundoNombre = model.SegundoNombre,
                    PrimerApellido = model.PrimerApellido,
                    SegundoApellido = model.SegundoApellido,
                    UserName = model.UserName,
                    Email = model.Email,
                    CreatedBy = User.Identity.GetUserId(),
                    ModifiedBy = User.Identity.GetUserId(),
                    CreatedAt = DateTime.Now,
                    ModifiedAt = DateTime.Now,
                    CreatedFrom = RequestHelpers.GetClientIpAddress(Request),
                    ModifiedFrom = RequestHelpers.GetClientIpAddress(Request)
                };
                var result = await UserManager.CreateAsync(user, model.Password);

                //Add User to the selected Groups 
                if (result.Succeeded)
                {
                    if (selectedGroups != null)
                    {
                        await GroupManager.SetUserGroupsAsync(user.Id, selectedGroups);
                    }
                    return RedirectToAction("Index");
                }
            }
            ViewBag.GroupsList = new SelectList(await GroupManager.Groups.ToListAsync(), "Id", "Name");
            model.Password = "";
            model.ConfirmPassword = "";
            return View(model);
        }


        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // Display a list of available Groups:
            var allGroups = GroupManager.Groups;
            var userGroups = await GroupManager.GetUserGroupsAsync(id);

            var model = new EditApplicationUserViewModel
            {
                Id = id,
                PrimerNombre = user.PrimerNombre,
                SegundoNombre = user.SegundoNombre,
                PrimerApellido = user.PrimerApellido,
                SegundoApellido = user.SegundoApellido,
                UserName = user.UserName,
                Email = user.Email,
            };

            var applicationGroups = userGroups as IList<ApplicationGroup> ?? userGroups.ToList();
            foreach (var group in allGroups)
            {
                var listItem = new SelectListItem
                {
                    Text = group.Name,
                    Value = group.Id,
                    Selected = applicationGroups.Any(g => g.Id == group.Id)
                };
                model.GroupsList.Add(listItem);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditApplicationUserViewModel model, 
            params string[] selectedGroups)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                // Update the User:
                user.PrimerNombre = model.PrimerNombre;
                user.SegundoNombre = model.SegundoNombre;
                user.PrimerApellido = model.PrimerApellido;
                user.SegundoApellido = model.SegundoApellido;
                user.UserName = model.UserName;
                user.Email = model.Email;
                user.ModifiedBy = User.Identity.GetUserId();
                user.ModifiedAt = DateTime.Now;
                user.ModifiedFrom = RequestHelpers.GetClientIpAddress(Request);
                await UserManager.UpdateAsync(user);

                // Update the Groups:
                if (selectedGroups != null)
                {
                    await GroupManager.SetUserGroupsAsync(user.Id, selectedGroups);
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Algo falló.");
            return View();
        }


        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userViewModel = new ApplicationUserViewModel
            {
                PrimerNombre = user.PrimerNombre,
                PrimerApellido = user.PrimerApellido,
                UserName = user.UserName
            };
            return View(userViewModel);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }

EventosCatolicos/Views/UsersAdmin/Create.cshtml
@model EventosCatolicos.ViewModels.ApplicationUserViewModel
@{
    ViewBag.Title = "Crear";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>@ViewBag.Title.</h2>

    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>Crear un nuevo usuario.</h4>
        <hr />
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.PrimerNombre, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.PrimerNombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PrimerNombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.SegundoNombre, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.SegundoNombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SegundoNombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.PrimerApellido, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.PrimerApellido, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.SegundoApellido, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.SegundoApellido, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.Email,"Correo Electrónico", new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-6">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-6">
            @Html.LabelFor(m => m.ConfirmPassword,"Confirmar Constraseña", new { @class = "control-label" })
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
        <div class="clearfix"></div>
        <hr />
        <div class="form-group">
            <label class="col-md-4 control-label">
                Seleccione los grupos del usuario.
            </label>
            <div class="col-md-8" style="margin-bottom: 35px">
                @foreach (var item in (SelectList)ViewBag.GroupsList)
                {
                    <div>
                        <input type="checkbox" name="selectedGroups" value="@item.Value" class="checkbox-inline" />
                        @Html.Label(item.Text, new { @class = "control-label" })
                    </div>
                }
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="form-group">
            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "UsersAdmin", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
            </div>
        </div>
    }

    @section Scripts {
        </div>
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/UsersAdmin/Delete.cshtml
@model EventosCatolicos.ViewModels.ApplicationUserViewModel

@{
    ViewBag.Title = "Eliminar";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Eliminar.</h2>

    <h3>Esta seguro que desea eliminar a este usuario?</h3>
    <div>
        <h4>User.</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PrimerNombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PrimerNombre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PrimerApellido)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PrimerApellido)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="btn-group" role="group" aria-label="...">
                @Html.ActionLink(" ", "Index", "UsersAdmin", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
                <button type="submit" class="btn btn-default color-rojo @EventosCatolicos.Servicios.clsOpciones.SIconoEliminar" data-toggle="tooltip" title="Eliminar "></button>
            </div>
        }
    </div>
    @section scripts
{
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}

EventosCatolicos/Views/UsersAdmin/Details.cshtml
@model EventosCatolicos.ViewModels.DetailsApplicationUserViewModel
@{
    ViewBag.Title = "Detalles";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Detalles.</h2>

    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PrimerNombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PrimerNombre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SegundoNombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SegundoNombre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PrimerApellido)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PrimerApellido)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SegundoApellido)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SegundoApellido)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CreatedFrom)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreatedFrom)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ModifiedBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ModifiedBy)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ModifiedAt)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ModifiedAt)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ModifiedFrom)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ModifiedFrom)
            </dd>
        </dl>
    </div>
    <h4>Grupos a los que el usuario pertenece:</h4>
    @if (@Model.GroupsCount == 0)
    {
        <hr />
        <p>No hay Grupos para este usuario.</p>
    }

    <table class="table">
        @foreach (var item in @Model.GroupsList)
        {
            <tr>
                <td>
                    @item.Name
                </td>
            </tr>
        }
    </table>
    <p>
        <div class="btn-group" role="group" aria-label="...">
            @Html.ActionLink(" ", "Index", "UsersAdmin", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon glyphicon-arrow-left color-verde" })
            @Html.ActionLink(" ", "Edit", "UsersAdmin", new { id = Model.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn btn-default " + @EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
        </div>
    </p>
    @section scripts
{
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip" ]').tooltip();
        });
    </script>
}

EventosCatolicos/Views/UsersAdmin/Edit.cshtml
@model EventosCatolicos.ViewModels.EditApplicationUserViewModel

@{
    ViewBag.Title = "Editar";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>@ViewBag.Title</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <h4>Editar Usuario</h4>
        <hr />
        @Html.ValidationSummary("", new { @class = "alert-danger" })
        @Html.HiddenFor(model => model.Id) 
        <div class="form-group col-sm-6 col-md-4"> 
            @Html.LabelFor(m => m.PrimerNombre, new { @class = "control-label" }) 
            @Html.TextBoxFor(m => m.PrimerNombre, new { @class = "form-control" }) 
            @Html.ValidationMessageFor(model => model.PrimerNombre, "", new { @class = "text-danger" }) 
        </div> 
        <div class="form-group col-sm-6 col-md-4"> 
            @Html.LabelFor(m => m.SegundoNombre, new { @class = "control-label" }) 
            @Html.TextBoxFor(m => m.SegundoNombre, new { @class = "form-control" }) 
            @Html.ValidationMessageFor(model => model.SegundoNombre, "", new { @class = "text-danger" }) 
        </div> 
        <div class="form-group col-sm-6 col-md-4"> 
            @Html.LabelFor(m => m.PrimerApellido, new { @class = "control-label" }) 
            @Html.TextBoxFor(m => m.PrimerApellido, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.SegundoApellido, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.SegundoApellido, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.Email, "Correo Electrónico", new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-sm-6 col-md-4">
            @Html.LabelFor(m => m.ConfirmPassword, "Confirmar Contraseña", new { @class = "control-label" })
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
        <div class="clearfix"></div>
        <hr />
        <div class="form-group">
            @Html.Label("Este usuario pertenece a los siguientes grupos", new { @class = "control-label col-md-4" })
            <div class="col-md-8" style="margin-bottom: 35px">
                @Html.EditorFor(m => @Model.GroupsList)
                @*foreach (var item in Model.GroupsList)
                    {
                        <input type="checkbox" name="selectedGroups" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                        @Html.Label(item.Text, new { @class = "control-label" })
                    }*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    }

    <div class="form-group col-md-10">
        <div class="btn-group" role="group" aria-label="...">
            @Html.ActionLink(" ", "Index", "UsersAdmin", null, new { data_toggle = "tooltip", title = "Regresar", @class = "btn btn-default glyphicon  glyphicon glyphicon-arrow-left color-verde" })
            <button type="submit" class="btn btn-default imagenGuardar color-azul" data-toggle="tooltip" title="Guardar"></button>
        </div>
    </div>

    @section Scripts {
        </div>
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    }

EventosCatolicos/Views/UsersAdmin/Index.cshtml
@model IEnumerable<EventosCatolicos.ViewModels.ApplicationUserViewModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Índice";
}
<div class="bs-callout bs-callout-danger" id="callout-progress-animation-css3">
    <h2>Índice</h2>

    <p>
        <a class="btn btn-default1" data-toggle="tooltip" title="Crear"
           href="@Url.Action("Create", new {controller = "UsersAdmin"})">
            <span class=" glyphicon glyphicon-plus color-verde" aria-hidden="true"></span>
            Crear
        </a>
    </p>
    <div class="horizontal-scroll">
        @Html.Grid(Model).Named("TipoSangre").EmptyText("No hay elementos para mostrar").Columns(columns =>
        {
            columns.Add().Titled("Opciones").Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(e =>
                @<span>
                    @Html.ActionLink(" ", "Edit", new { id = e.Id }, new { data_toggle = "tooltip", title = "Editar", @class = "btn1 btn-default1 " + EventosCatolicos.Servicios.clsOpciones.SIconoEditar })
                    @Html.ActionLink(" ", "Details", new { id = e.Id }, new { data_toggle = "tooltip", title = "Detalles", @class = "btn1 btn-default1 color-azul" + EventosCatolicos.Servicios.clsOpciones.SIconoDetalles })
                    @Html.ActionLink(" ", "Delete", new { id = e.Id }, new { data_toggle = "tooltip", title = "Eliminar", @class = "btn1 btn-default1 color-rojo " + EventosCatolicos.Servicios.clsOpciones.SIconoEliminar })
                </span>).SetWidth(200);
            columns.Add(model => model.UserName).Titled("Usuario").SetWidth(110);
            columns.Add(model => model.PrimerNombre).Titled("Primer Nombre").SetWidth(110);
            columns.Add(model => model.SegundoNombre).Titled("Segundo Nombre").SetWidth(110);
            columns.Add(model => model.PrimerApellido).Titled("Primer Apellido").SetWidth(110);
            columns.Add(model => model.SegundoApellido).Titled("Segundo Apellido").SetWidth(110);
            columns.Add(model => model.Email).Titled("Correo Electrónico").SetWidth(110);
            //.Titled("Opciones") added
        }).Filterable(true).WithMultipleFilters().Sortable(true).SetLanguage("es").Selectable(true)
    </div>

    @section scripts
{
        </div>
        @Scripts.Render("~/bundles/gridmvc")
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                pageGrids.TipoSangre.lang = gridmvc.lang.es;
            });
        </script>
    }